// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/9/13 14:04:11
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/Project/AI项目/个人博客/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Project/AI项目/个人博客/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Project/AI项目/个人博客/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Project/AI项目/个人博客/plugins/**/*.{js,ts,mjs}","D:/Project/AI项目/个人博客/composables/**/*.{js,ts,mjs}","D:/Project/AI项目/个人博客/utils/**/*.{js,ts,mjs}","D:/Project/AI项目/个人博客/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Project/AI项目/个人博客/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Project/AI项目/个人博客/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Project/AI项目/个人博客/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["content"]["files"]["22"] = "D:/Project/AI项目/个人博客/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})();

export default resolvedConfig;