// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2025/9/12 19:24:26
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
import cfg3 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["D:/Project/AI_PROJECT/GE_REN_XIANGMU/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Project/AI_PROJECT/GE_REN_XIANGMU/components/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Project/AI_PROJECT/GE_REN_XIANGMU/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Project/AI_PROJECT/GE_REN_XIANGMU/plugins/**/*.{js,ts,mjs}","D:/Project/AI_PROJECT/GE_REN_XIANGMU/composables/**/*.{js,ts,mjs}","D:/Project/AI_PROJECT/GE_REN_XIANGMU/utils/**/*.{js,ts,mjs}","D:/Project/AI_PROJECT/GE_REN_XIANGMU/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","D:/Project/AI_PROJECT/GE_REN_XIANGMU/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","D:/Project/AI_PROJECT/GE_REN_XIANGMU/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","D:/Project/AI_PROJECT/GE_REN_XIANGMU/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = (() => {const cfg=config;cfg["content"]["files"]["22"] = "D:/Project/AI_PROJECT/GE_REN_XIANGMU/.nuxt/content-cache/parsed/**/*.{md,yml,yaml,json}";;return cfg;})();

export default resolvedConfig;